Add squash-into-previous command

diff --git a/gh-pr-chain b/gh-pr-chain
--- a/gh-pr-chain
+++ b/gh-pr-chain
@@ -22,21 +22,28 @@ Help()
    echo "A chain of PRs is where one PR is based upon another, which in turn"
    echo "is based on another, and so on."
    echo
-   echo "Syntax: gh pr-chain [next|my-next|previous|merge-previous|merge-up-chain|create|insert]"
+   echo "Syntax: gh pr-chain [next|my-next|previous|merge-previous|merge-up-chain|create|insert|squash-into-previous]"
    echo 
-   echo "next               Go to a PR that is based on this PR"
-   echo "my-next            Go to a PR that is based on this PR and that I authored"
-   echo "previous           Go to the PR that this PR is based upon"
-   echo "merge-previous     Git merge changes from the branch that this PR is based upon"
-   echo "merge-up-chain     Merge changes from this branch up into the next PR. Then pushes. Then repeats up the chain."
-   echo "create 'PR Title'  Create a draft PR that is based on this PR"
-   echo "                   This will also create then checkout a branch with the same name."
-   echo "insert 'PR Title'  Insert a draft PR _before_ this PR"
-   echo "                   This will also create then checkout a branch with the same name."
-   echo "                   It will also change this PR to be based on the newly created PR."
+   echo "next                 Go to a PR that is based on this PR"
+   echo "my-next              Go to a PR that is based on this PR and that I authored"
+   echo "previous             Go to the PR that this PR is based upon"
+   echo "merge-previous       Git merge changes from the branch that this PR is based upon"
+   echo "merge-up-chain       Merge changes from this branch up into the next PR. Then pushes. Then repeats up the chain."
+   echo "create 'PR Title'    Create a draft PR that is based on this PR"
+   echo "                     This will also create then checkout a branch with the same name."
+   echo "insert 'PR Title'    Insert a draft PR _before_ this PR"
+   echo "                     This will also create then checkout a branch with the same name."
+   echo "                     It will also change this PR to be based on the newly created PR."
+   echo "squash-into-previous This will squash merge this PR into its base branch."
+   echo "                     It will check the PR has been approved."
+   echo "                     It will use the PR title and body for the commit title and body."
+   echo "                     It will close the PR and delete the branch."
    echo 
    echo "File issues at https://github.com/tamc/gh-pr-chain"
 }
+
+# Bash escaping can be a bit tricky. This helps to insert newlines into strings
+NEWLINE=$'\n'
 
 # First argument is the author. @me means current user. blank means any user.
 Next()
@@ -139,6 +146,27 @@ Insert()
   gh pr edit "$STARTING_PR_NUMBER" --base "$CURRENT_BRANCH"
 }
 
+SquashIntoPrevious()
+{
+  # Check PR has been approved
+  local PR=$(gh pr view --json reviewDecision,title,number,body,url)
+  local REVIEW_DECISION=$(echo "$PR" | jq -r ".reviewDecision")
+  if [ "$REVIEW_DECISION" != "APPROVED" ]
+  then
+    echo "PR has not been approved. Merge aborted."
+    exit 1
+  fi
+  # Gather information about this PR ready to make the squash commit
+  local PR_NUMBER=$(echo "$PR" | jq -r ".number")
+  local PR_TITLE=$(echo "$PR" | jq -r ".title")
+  local PR_BODY=$(echo "$PR" | jq -r ".body")
+  local PR_URL=$(echo "$PR" | jq -r ".url")
+  local COMMIT_TITLE="$PR_TITLE (#$PR_NUMBER)"
+  local COMMIT_BODY="$PR_BODY$NEWLINE$NEWLINE$PR_URL"
+  
+  gh pr merge --squash --subject "$COMMIT_TITLE" --body "$COMMIT_BODY" --delete-branch
+}
+
 case $1 in 
   next) # Go to the next PR
         Next
@@ -175,6 +203,9 @@ case $1 in
     fi
         Insert "$2" # Note it is important to quote $2 otherwise will split into multiple arguments on whitespace
         exit;;
+  squash-into-previous) # Squash merge into base branch, close PR, delete branch
+    SquashIntoPrevious
+    exit;;
   -v|--version) # Show the current version of this script
         Version 
         exit;;
